version: "3.9"
services:
    server:
      build: ./server/.
      ports: 
        - 9090:9090
      env_file:
        - ./env/server.env
      mem_limit: 50m
      depends_on:
        - postgres
      links:
        - postgres
      command: [ "./wait-for-it.sh", "postgres:5432", "--", "./server" ]
        
    tester:
      build: ./tester/.
      ports: 
        - 9010:9010
      mem_limit: 50m
      depends_on:
        - server
      links:
        - server
      command: [ "./wait-for-it.sh", "server:9090", "--", "./tester" ]

    postgres:
      image: postgres:latest
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: "12345"
        POSTGRES_DB: bitburst
      volumes:
        - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      command: -p 5432 -c log_statement=all
